name: Lint and Test Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  package-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          PATH=$HOME/.poetry/bin:$PATH NODE_ENV= poetry install
      - name: Lint
        run: |
          PATH=$HOME/.poetry/bin:$PATH poetry run flake8
      - name: Test
        run: |
          PATH=$HOME/.poetry/bin:$PATH poetry run py.test -v
